version: '3.8'
networks:
  app_network:
    driver: bridge
services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: mariadb.Dockerfile
    ports:
      - "3306:3306"
    networks:
      - app_network
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: wildfly.Dockerfile
    ports:
      - "9990:9990"
      - "8443:8443"
    restart: always
    networks:
      - app_network
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
     context: frontend
     dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend
