version: '3.8'
networks:
  app_network:
    driver: bridge
services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: mariadb.Dockerfile
    expose:
      - "3306"
    networks:
      - app_network
    volumes:
      - ./mariadb:/var/lib/mysql
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: wildfly.Dockerfile
    expose:
      - "9990"
      - "8080"
      - "8443"
    restart: always
    networks:
      - app_network
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
     context: frontend
     dockerfile: Dockerfile
    expose:
      - "3000"
    privileged: true
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://tua2021.pl/api/
      - VIRTUAL_HOST=tua2021.pl
      - VIRTUAL_PORT=3000

  nginx-proxy:
    container_name: nginx-proxy
    image: docker.io/jwilder/nginx-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./cert:/etc/nginx/certs
    networks:
      - app_network
    depends_on:
      - frontend
