version: '3.8'
networks:
  internal_network:
    driver: overlay
    internal: true
  external_network:
    driver: bridge
services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: mariadb.Dockerfile
    ports:
      - "3306:3306"
    networks:
      - internal_network
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: wildfly.Dockerfile
    ports:
      - "9990:9990"
      - "8443:8443"
    restart: always
    networks:
      - internal_network
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
     context: frontend
     dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - internal_network
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=tua2021.pl
      - LETSENCRYPT_HOST=tua2021.pl
      - LETSENCRYPT_EMAIL=szerszen@onet.pl

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:latest
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:ro
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    networks:
      - internal_network
      - external_network
    restart: always

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    privileged: true
    networks:
      - internal_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /apps/docker-articles/nginx/vhost.d:/etc/nginx/vhost.d
      - /apps/docker-articles/nginx/certs:/etc/nginx/certs:rw
      - /apps/docker-articles/nginx/html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

